version: 2
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingDirectory getting started demo
#-
#-                          +---------------+
#-                          |PingDataConsole|
#-                          +---------------+
#-                                  |
#-                          +----------------+
#-                          | PingDirectory  |
#-                          +----------------+
#-
#- To view PingData Console goto:
#- 
#-    https://localhost:8443/
#-    
#-      Server: pingdirectory
#-    Username: administrator
#-    Password: 2FederateM0re
#-
#- To view users in Ping Directory (via REST) goto:
#-    https://localhost:1443/directory/v1/ou=people,dc=example,dc=com/subtree?searchScope=singlelevel
#-
#-    Username: cn=administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

services:
  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingdirectory
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_ACCEPT_EULA=${PING_IDENTITY_ACCEPT_EULA}
      - MAX_HEAP_SIZE=${MAX_HEAP_SIZE}
      - ENV_VAR_WITH_SELECT_VALUE=${ENV_VAR_WITH_SELECT_VALUE}
    #env_file:
    #  - ./.pingidentity/devops
    networks:
      - pingnet
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "1389:389"
      - "1636:636"
      - "1443:443"
    volumes:
      - pingdirectory-out:/opt/out
      
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - "8443:8443"
    networks: 
      - pingnet
                    
networks:
  pingnet:

volumes:
  pingdirectory-out: